name: "cld"

services:
  mongodb:
    image: mongo:7
    container_name: cloud-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}:/data/db
    networks:
      - cloud-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: ${ME_CONFIG_BASICAUTH}
    depends_on:
      - mongodb
    networks:
      - cloud-network

  backend:
    build: ./backend
    container_name: cloud-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - cloud-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/presence_monitor

  frontend:
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE}
      args:
        - API_URL=${API_URL}
    container_name: cloud-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend/src:/app/src:ro
    depends_on:
      - backend
    networks:
      - cloud-network



networks:
  cloud-network:
    driver: bridge



