name: st-loc

services:
  postgres:
    image: postgres:15
    container_name: agent-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ${DATA_PATH}/data:/var/lib/postgresql/data
    networks:
      - st-agent

  redis:
    image: redis:7-alpine
    container_name: agent-redis
    ports:
      - "6379:6379"
    networks:
      - st-agent

  django-agent:
    build: .
    container_name: django-agent
    cap_add:
      - NET_RAW
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    network_mode: host

networks:
  st-agent:
    driver: bridge
