name: st-loc

services:
  postgres:
    image: postgres:15
    container_name: agent-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_PATH}/data:/app/data
    networks:
      - st-agent

  redis:
    image: redis:7-alpine
    container_name: agent-redis
    ports:
      - "6379:6379"
    networks:
      - st-agent

  django-agent:
    build: .
    container_name: django-agent
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - st-agent

networks:
  st-agent:
    driver: bridge
